'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, BookOpen, BrainCircuit, CalendarDays, CheckCircle2, ChevronRight, CircleGauge, ClipboardList, Clock3, Gamepad2, Home, Menu, Settings2, Sparkles, Target, X } from 'lucide-react';
import { getPhase, getPrescription, type Domain } from '@/lib/plan';
import { getSupabase } from '@/lib/supabase';

type View = 'today' | 'season' | 'progress' | 'journal';
type Log = { key:string; date:string; week:number; day:number; domain:Domain; minutes:number; difficulty:number; focus:number; performance:number; learned:string; notes:string; completedAt:string };
const nav = [{id:'today',label:'Hoje',icon:Home},{id:'season',label:'Temporada',icon:CalendarDays},{id:'progress',label:'Evolução',icon:BarChart3},{id:'journal',label:'Diário',icon:BookOpen}] as const;
const localDate=(d=new Date())=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(d);
function coords(){const start=new Date('2026-09-08T00:00:00-03:00');const now=new Date(`${localDate()}T12:00:00-03:00`);const n=Math.max(0,Math.floor((now.getTime()-start.getTime())/86400000));return {week:Math.min(26,Math.floor(n/7)+1),day:Math.min(6,(n%7)+1)}}

export default function HomePage(){
 const c=coords(); const [view,setView]=useState<View>('today'); const [week,setWeek]=useState(c.week); const [day,setDay]=useState(c.day); const [logs,setLogs]=useState<Log[]>([]); const [menu,setMenu]=useState(false);
 useEffect(()=>{const raw=localStorage.getItem('orbita-logs-v2'); if(raw) setLogs(JSON.parse(raw));},[]);
 useEffect(()=>{localStorage.setItem('orbita-logs-v2',JSON.stringify(logs));},[logs]);
 const save=async(log:Log)=>{setLogs(p=>[log,...p.filter(x=>x.key!==log.key)]);const s=getSupabase();if(!s)return;const {data}=await s.auth.getUser();if(!data.user)return;await s.from('orbita_session_logs').upsert({user_id:data.user.id,session_key:log.key,session_date:log.date,week_number:log.week,day_number:log.day,domain:log.domain,minutes:log.minutes,difficulty:log.difficulty,focus:log.focus,performance:log.performance,learned:log.learned,notes:log.notes,completed_at:log.completedAt},{onConflict:'user_id,session_key'});};
 const completed=new Set(logs.map(l=>l.key));
 return <main className="shell"><aside className={`sidebar ${menu?'open':''}`}><div className="brandRow"><div className="brand"><span className="orbitMark">◎</span> ÓRBITA</div><button className="icon mobileOnly" onClick={()=>setMenu(false)}><X/></button></div><p className="seasonTag">TEMPORADA 1 · FUNDAÇÃO</p><nav>{nav.map(({id,label,icon:Icon})=><button key={id} className={view===id?'active':''} onClick={()=>{setView(id);setMenu(false)}}><Icon/><span>{label}</span></button>)}</nav><div className="sideCard"><span>PRINCÍPIO</span><strong>O Órbita não é o exercício.</strong><p>Ele diz o que fazer, onde fazer, por quanto tempo e o que registrar.</p></div><div className="sideFooter"><Settings2/>26 semanas · 6 dias/semana</div></aside><section className="content"><header className="topbar"><button className="icon mobileOnly" onClick={()=>setMenu(true)}><Menu/></button><div><small>PROGRAMA COGNITIVO LONGITUDINAL</small><strong>Temporadas de 6 meses com progressão de dificuldade</strong></div><div className="topStat"><CheckCircle2/>{logs.length} sessões registradas</div></header>{view==='today'&&<Today week={week} day={day} setDay={setDay} logs={logs} onSave={save}/>} {view==='season'&&<Season week={week} setWeek={w=>{setWeek(w);setView('today')}} completed={completed}/>} {view==='progress'&&<Progress logs={logs}/>} {view==='journal'&&<Journal logs={logs}/>}</section></main>
}

function Today({week,day,setDay,logs,onSave}:{week:number;day:number;setDay:(d:number)=>void;logs:Log[];onSave:(l:Log)=>void}){
 const phase=getPhase(week),p=getPrescription(week,day),key=`s1-w${week}-d${day}`,existing=logs.find(l=>l.key===key); const [open,setOpen]=useState(false); const [difficulty,setDifficulty]=useState(existing?.difficulty??5);const [focus,setFocus]=useState(existing?.focus??5);const [performance,setPerformance]=useState(existing?.performance??5);const [minutes,setMinutes]=useState(existing?.minutes??p.minutes);const [learned,setLearned]=useState(existing?.learned??'');const [notes,setNotes]=useState(existing?.notes??'');
 useEffect(()=>{const e=logs.find(l=>l.key===`s1-w${week}-d${day}`),n=getPrescription(week,day);setDifficulty(e?.difficulty??5);setFocus(e?.focus??5);setPerformance(e?.performance??5);setMinutes(e?.minutes??n.minutes);setLearned(e?.learned??'');setNotes(e?.notes??'');setOpen(false)},[week,day,logs]);
 const dates=useMemo(()=>Array.from({length:6},(_,i)=>8+(week-1)*7+i),[week]);
 return <div className="page"><div className="eyebrow">SEMANA {week} DE 26 · {phase.name.toUpperCase()} · DIFICULDADE {p.level}/10</div><div className="hero"><div><h1>Manual do dia</h1><p>{phase.detail}</p></div><div className="timePill"><Clock3/><b>{p.minutes}</b><span>min</span></div></div><div className="dayTabs">{['TER','QUA','QUI','SEX','SÁB','DOM'].map((label,i)=><button key={label} className={day===i+1?'active':''} onClick={()=>setDay(i+1)}><span>{label}</span><b>{dates[i]}</b>{logs.some(l=>l.key===`s1-w${week}-d${i+1}`)&&<i>✓</i>}</button>)}</div><section className="prescription"><div className="prescriptionTop"><div><span className="domain"><Target/>{p.domain}</span><h2>{p.title}</h2><p>{p.subtitle}</p></div><div className="level"><CircleGauge/><span>Nível</span><b>{p.level}</b></div></div><div className="instructionGrid"><div className="mainInstruction"><h3><ClipboardList/>O que fazer</h3>{p.steps.map((s,i)=><div className="step" key={s}><b>{String(i+1).padStart(2,'0')}</b><p>{s}</p></div>)}</div><aside className="rules"><h3><BrainCircuit/>Regra cognitiva</h3><p>{p.rule}</p><h3><Gamepad2/>Ambiente</h3><p>{p.environment}</p><h3><Sparkles/>O que registrar</h3><p>{p.record}</p></aside></div><button className="primary" onClick={()=>setOpen(!open)}>{existing?'VER / EDITAR REGISTRO':'REGISTRAR RESULTADO'}<ChevronRight/></button>{open&&<div className="logForm"><Metric label="Dificuldade percebida" value={difficulty} setValue={setDifficulty}/><Metric label="Concentração" value={focus} setValue={setFocus}/><Metric label="Desempenho percebido" value={performance} setValue={setPerformance}/><label>Tempo realizado (min)<input type="number" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label className="wide">O que aprendi hoje<textarea value={learned} onChange={e=>setLearned(e.target.value)} placeholder="Escreva com suas palavras."/></label><label className="wide">Observações / resultado objetivo<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Erros, acertos, resultado, estratégia, referências..."/></label><button className="save" onClick={()=>{onSave({key,date:localDate(),week,day,domain:p.domain,minutes,difficulty,focus,performance,learned,notes,completedAt:new Date().toISOString()});setOpen(false)}}><CheckCircle2/>Salvar sessão</button></div>}</section></div>
}
function Metric({label,value,setValue}:{label:string;value:number;setValue:(n:number)=>void}){return <label>{label}<div className="scale">{Array.from({length:10},(_,i)=>i+1).map(n=><button type="button" key={n} className={value===n?'selected':''} onClick={()=>setValue(n)}>{n}</button>)}</div></label>}
function Season({week,setWeek,completed}:{week:number;setWeek:(w:number)=>void;completed:Set<string>}){return <div className="page"><div className="eyebrow">TEMPORADA 1 · 26 SEMANAS · 156 SESSÕES</div><div className="hero"><div><h1>Mapa da temporada</h1><p>A dificuldade aumenta por autonomia, abstração, pressão, integração e transferência — não apenas por velocidade.</p></div></div><div className="phases">{[1,3,7,13,19,24,26].map(w=><div key={w}><b>{getPhase(w).name}</b><span>{getPhase(w).range}</span></div>)}</div><div className="weekGrid">{Array.from({length:26},(_,i)=>i+1).map(w=>{const count=Array.from({length:6},(_,d)=>completed.has(`s1-w${w}-d${d+1}`)).filter(Boolean).length;return <button key={w} className={w===week?'selected':''} onClick={()=>setWeek(w)}><small>SEMANA</small><b>{String(w).padStart(2,'0')}</b><span>{getPhase(w).name}</span><div className="dots">{Array.from({length:6},(_,d)=><i key={d} className={d<count?'done':''}/>)}</div></button>})}</div></div>}
function Progress({logs}:{logs:Log[]}){const domains:Domain[]=['Atenção','Flexibilidade','Visuoespacial','Raciocínio','Verbal','Matemática','Criatividade','Ciência'];const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;return <div className="page"><div className="eyebrow">EVOLUÇÃO LONGITUDINAL</div><div className="hero"><div><h1>Seu desenvolvimento</h1><p>O Órbita acompanha desempenho nas atividades. Ele não converte prática diária em “pontos de QI”.</p></div></div>{logs.length===0?<Empty text="Ainda não há resultados. A temporada começa realmente zerada."/>:<div className="domainGrid">{domains.map(d=>{const rows=logs.filter(l=>l.domain===d);return <article key={d}><span>{d}</span><b>{rows.length}</b><small>sessões</small><div><em>Foco {avg(rows.map(r=>r.focus)).toFixed(1)}</em><em>Desempenho {avg(rows.map(r=>r.performance)).toFixed(1)}</em></div></article>})}</div>}</div>}
function Journal({logs}:{logs:Log[]}){return <div className="page"><div className="eyebrow">DIÁRIO ÓRBITA</div><div className="hero"><div><h1>Histórico de sessões</h1><p>Registro do que você fez, percebeu e aprendeu ao longo das temporadas.</p></div></div>{logs.length===0?<Empty text="Nenhuma sessão registrada ainda."/>:<div className="journal">{logs.map(l=><article key={l.key}><div><small>SEM {l.week} · DIA {l.day}</small><b>{l.domain}</b><span>{l.date}</span></div><div className="chips"><span>Foco {l.focus}/10</span><span>Dificuldade {l.difficulty}/10</span><span>{l.minutes} min</span></div>{l.learned&&<p><strong>Aprendi:</strong> {l.learned}</p>}{l.notes&&<p>{l.notes}</p>}</article>)}</div>}</div>}
function Empty({text}:{text:string}){return <div className="empty"><BrainCircuit/><h3>Sem dados ainda</h3><p>{text}</p></div>}
